In [5]:
def parse_documents(filename):
    with open(filename, "r", encoding="utf-8") as f:
        lines = f.readlines()
    lines = [line.strip() for line in lines]
    return lines 

l = parse_documents('requirements.txt')
l

['python-dotenv', 'numpy', 'pandas']

In [9]:

from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://harikrishnanv0591:c8hiZ5bohOzVRoj2@cluster0.5pb4dm2.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

SSL handshake failed: ac-igeqnto-shard-00-01.5pb4dm2.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-igeqnto-shard-00-02.5pb4dm2.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-igeqnto-shard-00-00.5pb4dm2.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 6830eb0bc52cd1033205cbe5, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-igeqnto-shard-00-00.5pb4dm2.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-igeqnto-shard-00-00.5pb4dm2.mongodb.

In [2]:
import pandas as pd
def csv_to_json(filepath):
    data = pd.read_csv(filepath)
    return data.to_dict(orient='records')


In [3]:
records = csv_to_json('artifacts\phisingData.csv')
len(records)

<>:1: SyntaxWarning: invalid escape sequence '\p'
<>:1: SyntaxWarning: invalid escape sequence '\p'
C:\Users\harik\AppData\Local\Temp\ipykernel_21684\3405935831.py:1: SyntaxWarning: invalid escape sequence '\p'
  records = csv_to_json('artifacts\phisingData.csv')


11055

In [12]:
import os
from dotenv import load_dotenv
def insert_data_mongodb(database_name, collection_name,filepath):
    
    load_dotenv()
    uri = os.getenv("MONGO_DB_URL") 
    
    
    # Create a new client and connect to the server
    client = MongoClient(uri, server_api=ServerApi('1'))
    database = client[database_name]
    collection = database[collection_name]
    records = csv_to_json(filepath)
    collection.insert_many(records)
    

In [13]:
insert_data_mongodb('Network_Security','Websites','artifacts\phisingData.csv')

<>:1: SyntaxWarning: invalid escape sequence '\p'
<>:1: SyntaxWarning: invalid escape sequence '\p'
C:\Users\harik\AppData\Local\Temp\ipykernel_21684\3591732485.py:1: SyntaxWarning: invalid escape sequence '\p'
  insert_data_mongodb('Network_Security','Websites','artifacts\phisingData.csv')


In [ ]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}

df = pd.DataFrame(data)
json_str = df.to_json(orient='records', )
print(json_str)
print(df.to_dict(orient='records'))

[{"Name":"Alice","Age":25,"City":"New York"},{"Name":"Bob","Age":30,"City":"Los Angeles"},{"Name":"Charlie","Age":35,"City":"Chicago"}]
[{'Name': 'Alice', 'Age': 25, 'City': 'New York'}, {'Name': 'Bob', 'Age': 30, 'City': 'Los Angeles'}, {'Name': 'Charlie', 'Age': 35, 'City': 'Chicago'}]


In [27]:
import yaml
from pathlib import Path
import os
from box import ConfigBox
def read_yaml(path_to_yaml: str) -> ConfigBox:
    try:
        with open(path_to_yaml, 'r') as file:
            content = yaml.safe_load(file)
            return ConfigBox(content)
    except Exception as e:
        print(e)
context = read_yaml('artifacts\schema\schema.yaml')
context.columns

<>:12: SyntaxWarning: invalid escape sequence '\s'
<>:12: SyntaxWarning: invalid escape sequence '\s'
C:\Users\harik\AppData\Local\Temp\ipykernel_21684\3995628551.py:12: SyntaxWarning: invalid escape sequence '\s'
  context = read_yaml('artifacts\schema\schema.yaml')


BoxList([{'having_IP_Address': 'int64'}, {'URL_Length': 'int64'}, {'Shortining_Service': 'int64'}, {'having_At_Symbol': 'int64'}, {'double_slash_redirecting': 'int64'}, {'Prefix_Suffix': 'int64'}, {'having_Sub_Domain': 'int64'}, {'SSLfinal_State': 'int64'}, {'Domain_registeration_length': 'int64'}, {'Favicon': 'int64'}, {'port': 'int64'}, {'HTTPS_token': 'int64'}, {'Request_URL': 'int64'}, {'URL_of_Anchor': 'int64'}, {'Links_in_tags': 'int64'}, {'SFH': 'int64'}, {'Submitting_to_email': 'int64'}, {'Abnormal_URL': 'int64'}, {'Redirect': 'int64'}, {'on_mouseover': 'int64'}, {'RightClick': 'int64'}, {'popUpWidnow': 'int64'}, {'Iframe': 'int64'}, {'age_of_domain': 'int64'}, {'DNSRecord': 'int64'}, {'web_traffic': 'int64'}, {'Page_Rank': 'int64'}, {'Google_Index': 'int64'}, {'Links_pointing_to_page': 'int64'}, {'Statistical_report': 'int64'}, {'Result': 'int64'}])

In [21]:
import pandas as pd

# Sample DataFrame
df = pd.DataFrame({
    'name': ['Alice', 'Bob'],
    'age': [25, 30],
    'salary': [50000.0, 60000.5],
    'is_manager': [False, True]
})

# Get column names and data types
column_info = [{col:str(dtype)} for col, dtype in df.dtypes.items()]
print(column_info)



[{'name': 'object'}, {'age': 'int64'}, {'salary': 'float64'}, {'is_manager': 'bool'}]


In [22]:
lst = [{'name': 'object'}, {'age': 'int64'}, {'salary': 'float64'}, {'is_manager': 'bool'}]
if len(lst) == len(column_info):
    for i in range(len(lst)):
        key1, values1 = list(lst[i].items())[0]
        key, value = list(column_info[i].items())[0]
        if (key == key1)  and (value ==values1):
            validation_status = True
validation_status


True

In [41]:
import pandas as pd
df = pd.read_csv(r'artifacts\data_transforamtion_directory\transformed_train_data.csv')
X = df.drop("Result",axis =1)
Y = df['Result']
from sklearn.feature_selection import SelectKBest, f_classif

# X: features, y: target
selector = SelectKBest(score_func=f_classif, k=15)  # Select top 10 features
X_new = selector.fit_transform(X, Y)

# Get selected feature indices or names
selected_features = selector.get_support(indices=True)


In [42]:
selected_features

array([ 0,  5,  6,  7,  8, 12, 13, 14, 15, 23, 24, 25, 26, 27, 29])

In [38]:
X.columns

Index(['having_IP_Address', 'URL_Length', 'Shortining_Service',
       'having_At_Symbol', 'double_slash_redirecting', 'Prefix_Suffix',
       'having_Sub_Domain', 'SSLfinal_State', 'Domain_registeration_length',
       'Favicon', 'port', 'HTTPS_token', 'Request_URL', 'URL_of_Anchor',
       'Links_in_tags', 'SFH', 'Submitting_to_email', 'Abnormal_URL',
       'Redirect', 'on_mouseover', 'RightClick', 'popUpWidnow', 'Iframe',
       'age_of_domain', 'DNSRecord', 'web_traffic', 'Page_Rank',
       'Google_Index', 'Links_pointing_to_page', 'Statistical_report'],
      dtype='object')

In [43]:
columns = [X.columns[i] for i in selected_features]
columns

['having_IP_Address',
 'Prefix_Suffix',
 'having_Sub_Domain',
 'SSLfinal_State',
 'Domain_registeration_length',
 'Request_URL',
 'URL_of_Anchor',
 'Links_in_tags',
 'SFH',
 'age_of_domain',
 'DNSRecord',
 'web_traffic',
 'Page_Rank',
 'Google_Index',
 'Statistical_report']

In [8]:
import pandas as pd
df = pd.read_excel('Data Processing Specialist Assignment data ver 1.xlsx')
duplicates = df.duplicated()
print(type(duplicates))
unique_count = duplicates.nunique()
print(unique_count)


<class 'pandas.core.series.Series'>
1


In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report,f1_score, recall_score
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

In [44]:
train_data = pd.read_csv(r'artifacts\data_transforamtion_directory\transformed_train_data.csv')
X_train = train_data.drop(columns='Result',axis=1)
y_train = train_data['Result']
test_data = pd.read_csv(r'artifacts\data_transforamtion_directory\transformed_test_data.csv')
X_test = test_data.drop(columns='Result',axis=1)
y_test = test_data['Result']
X_train = X_train[columns]
X_test = X_test[columns]

# 3. Feature Scaling (important for Logistic Regression and boosting)
# scaler = StandardScaler()
# X_train_scaled = scaler.fit_transform(X_train)
# X_test_scaled = scaler.transform(X_test)

# 4. Initialize models
models = {
    "Logistic Regression": LogisticRegression(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(),
    "AdaBoost": AdaBoostClassifier()
}
metrics ={}

# 5. Train, Predict, and Evaluate
for name, model in models.items():
    # Use scaled features for models that benefit from it
    if name in ["Logistic Regression", "Gradient Boosting", "AdaBoost"]:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
    else:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
    
    f1 = f1_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    print(f"\n===== {name} =====")
    print("Accuracy:", (accuracy_score(y_test, y_pred)))
    print("Confusion Matrix:\n", (confusion_matrix(y_test, y_pred)))
    

    print("F1 Score:", f1)
    print("Recall:", recall)

    print("Classification Report:\n", (classification_report(y_test, y_pred)))

    metrics[name] = {'Accuracy':accuracy_score(y_test, y_pred),'Confusion Matrix': confusion_matrix(y_test, y_pred),
                     "F1 Score": f1, "Recall": recall, "Classification Report":classification_report(y_test, y_pred)
                     }

    



===== Logistic Regression =====
Accuracy: 0.9222071460877431
Confusion Matrix:
 [[ 858   98]
 [  74 1181]]
F1 Score: 0.9321231254932912
Recall: 0.9410358565737051
Classification Report:
               precision    recall  f1-score   support

        -1.0       0.92      0.90      0.91       956
         1.0       0.92      0.94      0.93      1255

    accuracy                           0.92      2211
   macro avg       0.92      0.92      0.92      2211
weighted avg       0.92      0.92      0.92      2211


===== Decision Tree =====
Accuracy: 0.9493441881501583
Confusion Matrix:
 [[ 896   60]
 [  52 1203]]
F1 Score: 0.9555202541699762
Recall: 0.9585657370517928
Classification Report:
               precision    recall  f1-score   support

        -1.0       0.95      0.94      0.94       956
         1.0       0.95      0.96      0.96      1255

    accuracy                           0.95      2211
   macro avg       0.95      0.95      0.95      2211
weighted avg       0.95      0.

In [29]:
train_data = pd.read_csv(r'artifacts\data_transforamtion_directory\transformed_train_data.csv')
X_train = train_data.drop(columns='Result',axis=1)
y_train = train_data['Result']
test_data = pd.read_csv(r'artifacts\data_transforamtion_directory\transformed_test_data.csv')
X_test = test_data.drop(columns='Result',axis=1)
y_test = test_data['Result']

# 3. Feature Scaling (important for Logistic Regression and boosting)
# scaler = StandardScaler()
# X_train_scaled = scaler.fit_transform(X_train)
# X_test_scaled = scaler.transform(X_test)

# 4. Initialize models
models = {
    "Logistic Regression": LogisticRegression(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(),
    "AdaBoost": AdaBoostClassifier()
}
metrics ={}

# 5. Train, Predict, and Evaluate
for name, model in models.items():
    # Use scaled features for models that benefit from it
    if name in ["Logistic Regression", "Gradient Boosting", "AdaBoost"]:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
    else:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
    
    f1 = f1_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    print(f"\n===== {name} =====")
    print("Accuracy:", (accuracy_score(y_test, y_pred)))
    print("Confusion Matrix:\n", (confusion_matrix(y_test, y_pred)))
    

    print("F1 Score:", f1)
    print("Recall:", recall)

    print("Classification Report:\n", (classification_report(y_test, y_pred)))

    metrics[name] = {'Accuracy':accuracy_score(y_test, y_pred),'Confusion Matrix': confusion_matrix(y_test, y_pred),
                     "F1 Score": f1, "Recall": recall, "Classification Report":classification_report(y_test, y_pred)
                     }

    



===== Logistic Regression =====
Accuracy: 0.924468566259611
Confusion Matrix:
 [[ 865   91]
 [  76 1179]]
F1 Score: 0.9338613861386139
Recall: 0.9394422310756972
Classification Report:
               precision    recall  f1-score   support

        -1.0       0.92      0.90      0.91       956
         1.0       0.93      0.94      0.93      1255

    accuracy                           0.92      2211
   macro avg       0.92      0.92      0.92      2211
weighted avg       0.92      0.92      0.92      2211


===== Decision Tree =====
Accuracy: 0.9588421528720036
Confusion Matrix:
 [[ 909   47]
 [  44 1211]]
F1 Score: 0.9637883008356546
Recall: 0.9649402390438248
Classification Report:
               precision    recall  f1-score   support

        -1.0       0.95      0.95      0.95       956
         1.0       0.96      0.96      0.96      1255

    accuracy                           0.96      2211
   macro avg       0.96      0.96      0.96      2211
weighted avg       0.96      0.9

In [18]:
metrics

{'Logistic Regression': {'Accuracy': 0.924468566259611,
  'Confusion Matrix': array([[ 865,   91],
         [  76, 1179]]),
  'F1 Score': 0.9338613861386139,
  'Recall': 0.9394422310756972,
  'Classification Report': '              precision    recall  f1-score   support\n\n        -1.0       0.92      0.90      0.91       956\n         1.0       0.93      0.94      0.93      1255\n\n    accuracy                           0.92      2211\n   macro avg       0.92      0.92      0.92      2211\nweighted avg       0.92      0.92      0.92      2211\n'},
 'Decision Tree': {'Accuracy': 0.9592944369063772,
  'Confusion Matrix': array([[ 909,   47],
         [  43, 1212]]),
  'F1 Score': 0.964200477326969,
  'Recall': 0.9657370517928286,
  'Classification Report': '              precision    recall  f1-score   support\n\n        -1.0       0.95      0.95      0.95       956\n         1.0       0.96      0.97      0.96      1255\n\n    accuracy                           0.96      2211\n   macro

In [ ]:
list_of_recall_score = {}
max =0
for model_name, metric_values in metrics.items():
    if metric_values['Recall'] > max:
        s = model_name
        max = metric_values['Recall']
list_of_recall_score

{'Logistic Regression': 0.9410358565737051,
 'Decision Tree': 0.9585657370517928,
 'Random Forest': 0.9713147410358566,
 'Gradient Boosting': 0.9593625498007968,
 'AdaBoost': 0.9482071713147411}

In [49]:
list_of_recall_score = {}
max =0
for model_name, metric_values in metrics.items():
    if metric_values['Recall'] > max:
        s = model_name
        max = metric_values['Recall']
list_of_recall_score[s] = max
list_of_recall_score


{'Random Forest': 0.9713147410358566}

In [19]:
from sklearn.model_selection import GridSearchCV

# Dictionary to store best models
best_models = {}

# 1. Logistic Regression
param_logreg = {
    'C': [0.01, 0.1, 1, 10],
    'penalty': ['l2'],  # 'l1' if solver='liblinear'
    'solver': ['lbfgs', 'liblinear']
}
grid_logreg = GridSearchCV(LogisticRegression(max_iter=1000), param_logreg, cv=5, scoring='recall')
grid_logreg.fit(X_train, y_train)
best_models['Logistic Regression'] = grid_logreg.best_estimator_

# 2. Decision Tree
param_tree = {
    'max_depth': [3, 5, 10, None],
    'min_samples_split': [2, 5, 10],
    'criterion': ['gini', 'entropy']
}
grid_tree = GridSearchCV(DecisionTreeClassifier(), param_tree, cv=5, scoring='recall')
grid_tree.fit(X_train, y_train)
best_models['Decision Tree'] = grid_tree.best_estimator_

# 3. Random Forest
param_rf = {
    'n_estimators': [100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5],
    'criterion': ['gini', 'entropy']
}
grid_rf = GridSearchCV(RandomForestClassifier(), param_rf, cv=5, scoring='recall')
grid_rf.fit(X_train, y_train)
best_models['Random Forest'] = grid_rf.best_estimator_

# 4. Gradient Boosting
param_gb = {
    'n_estimators': [100, 200],
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [3, 5]
}
grid_gb = GridSearchCV(GradientBoostingClassifier(), param_gb, cv=5, scoring='recall')
grid_gb.fit(X_train, y_train)
best_models['Gradient Boosting'] = grid_gb.best_estimator_

# 5. AdaBoost
param_ada = {
    'n_estimators': [50, 100, 200],
    'learning_rate': [0.01, 0.1, 1]
}
grid_ada = GridSearchCV(AdaBoostClassifier(), param_ada, cv=5, scoring='accuracy')
grid_ada.fit(X_train, y_train)
best_models['AdaBoost'] = grid_ada.best_estimator_


In [21]:
from sklearn.metrics import accuracy_score

for name, model in best_models.items():
    if name in ["Logistic Regression", "Gradient Boosting", "AdaBoost"]:
        y_pred = model.predict(X_test)
    else:
        y_pred = model.predict(X_test)
    f1 = f1_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    
    print(f"\nBest Model - {name}")
    print("F1 Score:", f1)
    print("Recall:", recall)
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Best Params:", model.get_params())



Best Model - Logistic Regression
F1 Score: 0.9348083761359146
Recall: 0.9426294820717132
Accuracy: 0.9253731343283582
Best Params: {'C': 0.1, 'class_weight': None, 'dual': False, 'fit_intercept': True, 'intercept_scaling': 1, 'l1_ratio': None, 'max_iter': 1000, 'multi_class': 'deprecated', 'n_jobs': None, 'penalty': 'l2', 'random_state': None, 'solver': 'lbfgs', 'tol': 0.0001, 'verbose': 0, 'warm_start': False}

Best Model - Decision Tree
F1 Score: 0.9365443425076453
Recall: 0.9760956175298805
Accuracy: 0.9249208502939846
Best Params: {'ccp_alpha': 0.0, 'class_weight': None, 'criterion': 'entropy', 'max_depth': 5, 'max_features': None, 'max_leaf_nodes': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'monotonic_cst': None, 'random_state': None, 'splitter': 'best'}

Best Model - Random Forest
F1 Score: 0.9715639810426541
Recall: 0.9800796812749004
Accuracy: 0.9674355495251018
Best Params: {'bootstrap': True, 'ccp_alpha

In [ ]:
import pickle
test_data = pd.read_csv(r'artifacts\data_transforamtion_directory\transformed_test_data.csv')
X_test = test_data[:5].drop(columns='Result',axis=1)
y_test = test_data[:5]['Result']
with open(r'artifacts\model_directory\best_model.pkl', 'rb') as file:
            loaded_model = pickle.load(file)
y_pred = loaded_model.predict(X_test)
print(y_pred)
print(y_test)


[-1. -1. -1.  1.  1.]
0   -1.0
1   -1.0
2   -1.0
3    1.0
4    1.0
Name: Result, dtype: float64


In [7]:
data = pd.read_csv(r'artifacts\data_ingestion_directory\raw_data\raw_data.csv')
for i in data.columns:
    print(f"{i} has unique values {data[i].unique()}")

having_IP_Address has unique values [-1  1]
URL_Length has unique values [ 1  0 -1]
Shortining_Service has unique values [ 1 -1]
having_At_Symbol has unique values [ 1 -1]
double_slash_redirecting has unique values [-1  1]
Prefix_Suffix has unique values [-1  1]
having_Sub_Domain has unique values [-1  0  1]
SSLfinal_State has unique values [-1  1  0]
Domain_registeration_length has unique values [-1  1]
Favicon has unique values [ 1 -1]
port has unique values [ 1 -1]
HTTPS_token has unique values [-1  1]
Request_URL has unique values [ 1 -1]
URL_of_Anchor has unique values [-1  0  1]
Links_in_tags has unique values [ 1 -1  0]
SFH has unique values [-1  1  0]
Submitting_to_email has unique values [-1  1]
Abnormal_URL has unique values [-1  1]
Redirect has unique values [0 1]
on_mouseover has unique values [ 1 -1]
RightClick has unique values [ 1 -1]
popUpWidnow has unique values [ 1 -1]
Iframe has unique values [ 1 -1]
age_of_domain has unique values [-1  1]
DNSRecord has unique values

In [1]:
from sklearn.metrics import confusion_matrix
import mlflow
import numpy as np

# Example ground truth and predictions
y_true = [0, 1, 0, 1]
y_pred = [0, 0, 0, 1]

# Compute confusion matrix
cm = confusion_matrix(y_true, y_pred)

# Convert to a string format
cm_text = '\n'.join(['\t'.join(map(str, row)) for row in cm])

with mlflow.start_run():
    mlflow.log_text(cm_text, "confusion_matrix.txt")


In [5]:
from pathlib import Path
type(Path.cwd().joinpath("artifacts/mlruns").as_uri())

str

In [5]:

import mlflow

# Set the tracking URI to the local mlruns directory
mlflow.set_tracking_uri(uri ="http://localhost:5000")

# Now load the model
model = mlflow.sklearn.load_model("models:/best_model/latest")

MlflowException: API request to http://localhost:5000/api/2.0/mlflow/registered-models/get-latest-versions failed with exception HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/2.0/mlflow/registered-models/get-latest-versions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002E96DF3F710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

In [13]:
from mlflow.tracking import MlflowClient

client = MlflowClient()

# Get latest version info for registered model
latest_versions = client.get_latest_versions("best_model", stages=["None", "Production", "Staging"])
print(len(latest_versions))

for version in latest_versions:
    print("Model Version:", version.version)
    print("Run ID:", version.run_id)
    print("Source Path:", version.source)
    s = version.source

print(s)



1
Model Version: 7
Run ID: d52f2d0fa9ce4cb3958ad491e9688019
Source Path: file:///D:/Network%20Security%20Project/Network-Security/artifacts/mlruns/d52f2d0fa9ce4cb3958ad491e9688019/artifacts/Random Forest
file:///D:/Network%20Security%20Project/Network-Security/artifacts/mlruns/d52f2d0fa9ce4cb3958ad491e9688019/artifacts/Random Forest


C:\Users\harik\AppData\Local\Temp\ipykernel_57376\4002227149.py:6: FutureWarning: ``mlflow.tracking.client.MlflowClient.get_latest_versions`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
  latest_versions = client.get_latest_versions("best_model", stages=["None", "Production", "Staging"])


In [1]:
dic = {
    'having_IP_Address' : [-1 , 1],
    'URL_Length' : [ 1,  0, -1],
    'Shortining_Service' : [ 1, -1],
    'having_At_Symbol' : [ 1, -1],
    'double_slash_redirecting' : [-1,  1],
    'Prefix_Suffix' : [-1,  1],
    'having_Sub_Domain' : [-1,  0,  1],
    'SSLfinal_State' : [-1,  1,  0],
    'Domain_registeration_length' : [-1 , 1],
    'Favicon' : [ 1, -1],
    'port' : [ 1 ,-1],
    'HTTPS_token' : [-1,  1],
    'Request_URL' : [ 1 ,-1],
    'URL_of_Anchor' : [-1,  0,  1],
    'Links_in_tags' : [ 1 ,-1 , 0],
    'SFH' : [-1  ,1  ,0],
    'Submitting_to_email' : [-1 , 1],
    'Abnormal_URL' : [-1 , 1],
    'Redirect' : [0 ,1],
    'on_mouseover' : [ 1 ,-1],
    'RightClick' : [ 1 ,-1],
    'popUpWidnow' : [ 1 -1],
    'Iframe' : [ 1, -1],
    'age_of_domain' : [-1  ,1],
    'DNSRecord' : [-1  ,1],
    'web_traffic' : [-1 , 0  ,1],
    'Page_Rank' : [-1 , 1],
    'Google_Index' : [ 1 ,-1],
    'Links_pointing_to_page' : [ 1,  0, -1],
    'Statistical_report' : [-1 , 1],
    'Result' : [-1 , 1]}

In [ ]:
import streamlit as st
import pandas as pd
left_column, right_column = st.columns(2)
# You can use a column just like st.sidebar:


dic = {
    'having_IP_Address' : [-1 , 1],
    'URL_Length' : [ 1,  0, -1],
    'Shortining_Service' : [ 1, -1],
    'having_At_Symbol' : [ 1, -1],
    'double_slash_redirecting' : [-1,  1],
    'Prefix_Suffix' : [-1,  1],
    'having_Sub_Domain' : [-1,  0,  1],
    'SSLfinal_State' : [-1,  1,  0],
    'Domain_registeration_length' : [-1 , 1],
    'Favicon' : [ 1, -1],
    'port' : [ 1 ,-1],
    'HTTPS_token' : [-1,  1],
    'Request_URL' : [ 1 ,-1],
    'URL_of_Anchor' : [-1,  0,  1],
    'Links_in_tags' : [ 1 ,-1 , 0],
    'SFH' : [-1  ,1  ,0],
    'Submitting_to_email' : [-1 , 1],
    'Abnormal_URL' : [-1 , 1],
    'Redirect' : [0 ,1],
    'on_mouseover' : [ 1 ,-1],
    'RightClick' : [ 1 ,-1],
    'popUpWidnow' : [ 1 -1],
    'Iframe' : [ 1, -1],
    'age_of_domain' : [-1  ,1],
    'DNSRecord' : [-1  ,1],
    'web_traffic' : [-1 , 0  ,1],
    'Page_Rank' : [-1 , 1],
    'Google_Index' : [ 1 ,-1],
    'Links_pointing_to_page' : [ 1,  0, -1],
    'Statistical_report' : [-1 , 1]}


    

2025-06-01 14:54:14.116 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-06-01 14:54:14.119 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-06-01 14:54:14.120 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.


ValueError: All arrays must be of the same length

In [4]:
import pickle
import pandas as pd
import sys
import os
from src.logging.logger import logger
from sklearn.metrics import accuracy_score
base_dir = os.path.dirname(__file__)
csv_path = os.path.join(base_dir, 'unit_test.csv')
model_path = os.path.join(base_dir, '..', 'artifacts', 'model_directory', 'best_model.pkl') 
test_data = pd.read_csv(csv_path) # r'unit_test\unit_test.csv'
X_test = test_data[:5].drop(columns='Result',axis=1)
y_test = test_data[:5]['Result']
with open(model_path, 'rb') as file: # r'artifacts\model_directory\best_model.pkl'
            loaded_model = pickle.load(file)
y_pred = loaded_model.predict(X_test)
model_accuracy = (accuracy_score(y_test, y_pred))

if model_accuracy >0.9:
        pass
else:
        logger.error("The accuracy is not upto the mark")
        sys.exit(1)

NameError: name '__file__' is not defined